import Head from 'next/head'
import HomepageHero from '../sections/HomepageHero/HomepageHero.component'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomepageHero bgImage='/images/background_1.png' />
    </div>
  )
}
